#!/bin/bash
# Purge Modules
module purge

# Load necessary dependencies on 
# Hypnos Cluster


module load gcc/5.3.0
module load cuda/8.0
module load cmake/3.3.0
module load openmpi/1.8.6
module load boost/1.62.0
module load libsodium
module load zeromq
module load hdf5-parallel
module load python/3.4.3
module load qt


